application: sigma-kayak-119906
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# Main App
- url: .*
  script: main.app
  secure: always
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest